### ISSUE TITLE
[todoapp][検証]ToDoアプリの動作検証

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#10]
## 概要
・ToDoアプリが正常に機能することを確認する。

## 計画
・検証項目と検証操作をまとめたテスト仕様書をExcelで作成する。
・検証項目は大まかに以下の内容を確認する。
①画面表示
②画面遷移
③ToDoの作成、編集、削除操作
④ToDoリストの表示

作業開始：7/12
作業終了：7/13

## ゴール
・検証項目をすべてクリアし、正常に機能することを確認する。

## OutPut
・[テスト仕様書](https://github.com/kaitoishii1217/ToDoApp/blob/main/TodoApp_%E3%83%86%E3%82%B9%E3%83%88%E4%BB%95%E6%A7%98%E6%9B%B8.xlsx)

**Comment by itpm-sakamoto** [comment]
テスト完了の為、Closeします。
