### ISSUE TITLE
[todoapp][FS]JDBCについての調査

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#2]
## 概要
・ToDoアプリで用いるJDBCについての調査

## 計画
・JDBC含めDBについて書籍で学ぶ：JDBCの種類、仕組み、使い方
・eclipceでJDBCを使うための方法について調査

作業開始：6/15
作業終了：6/19

## ゴール
・アプリを作るうえで必要なJDBCについての知識を習得する

## Output
[調査結果のドキュメント](https://github.com/kaitoishii1217/ToDoApp/blob/develop/document/jdbc.md)

**Comment by itpm-sakamoto** [comment]
調査完了の為、Closeします。
