### ISSUE TITLE
[todoapp][FS]DB操作のお試し実装

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#3]
## 概要
・DBのCRUD操作をお試し実装する。

## 計画
・ToDoアプリのためのテーブルを作成する。
・レコード作成のお試し実装
・レコード編集のお試し実装
・レコード削除のお試し実装

作業開始：6/15
作業終了：6/19

## ゴール
・DBの各操作のお試し実装が完了すること

## Output
・[レコード作成のお試し実装コード](https://github.com/kaitoishii1217/ToDoApp/blob/main/InsertTest.java)
・[レコード編集のお試し実装コード](https://github.com/kaitoishii1217/ToDoApp/blob/main/UpdateTest.java)
・[レコード削除のお試し実装コード](https://github.com/kaitoishii1217/ToDoApp/blob/main/DeleteTest.java)
・[レコード表示のお試し実装コード](https://github.com/kaitoishii1217/ToDoApp/blob/main/SelectTest.java)

**Comment by itpm-sakamoto** [comment]
お試し実装完了の為、Closeします。
