### ISSUE TITLE
[todoapp][FS]MySQLについての調査

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#4]
## 概要
・MySQLについての調査

## 計画
・インストール～環境設定
・使用方法：テーブルの作成方法

作業開始：6/13
作業終了：6/14

## ゴール
・MySQLのインストール方法、使用方法の理解

## Output
・[調査結果のドキュメント](https://github.com/kaitoishii1217/ToDoApp/blob/develop/document/mysql.md)

**Comment by itpm-sakamoto** [comment]
調査完了の為、Closeします。
