### ISSUE TITLE
[todoapp][設計]画面遷移図の作成

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#5]
## 概要
・ToDoアプリの画面遷移図を作成する。

## 計画
・作成はdrawioで行う。
・以下の観点で画面遷移図を作成する。
①何種類の画面があるか
②どの画面からどの画面に移動するか。

作業開始：6/20
作業終了：6/21

## ゴール
・画面遷移図を完成させる。

## OutPut
・[画面遷移図](https://github.com/kaitoishii1217/ToDoApp/blob/main/image/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB%E5%9B%B3.pdf)

**Comment by itpm-sakamoto** [comment]
画面遷移図作成完了の為、Closeします。
