### ISSUE TITLE
[todoapp][設計]クラス図の作成

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#6]
## 概要
・ToDoアプリのクラス図を作成する。

## 計画
・作成はdrawioで行う。
・以下の観点でクラス図を作成する。
①必要なクラス
②各クラスが持つ属性と操作
③各属性・操作にアクセス可能な範囲
④各クラスの関連性

作業開始：6/22
作業終了：6/26

## ゴール
・クラス図を完成させる。

## OutPut
・[クラス図](https://github.com/kaitoishii1217/ToDoApp/blob/main/image/20210717_%E3%82%AF%E3%83%A9%E3%82%B9%E5%9B%B3.pdf)

**Comment by itpm-sakamoto** [comment]
クラス図作成完了の為、Closeします。

**Comment by kaitoishii1217** [comment]
クラス図を一部修正したためリンクを替えました
