### ISSUE TITLE
[todoapp][設計]ER図の作成

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#7]
## 概要
・ToDoアプリ用データベースのER図を作成する。

## 計画
・以下の観点でER図を作成する。（IE記法）
①ToDoアプリに必要なデータを分類する。（エンティティ）
②各エンティティの属性を定義する。
②主キーを定める。
③エンティティの関連性を定める。（リレーション）

作業開始：6/27
作業終了：6/29

## ゴール
・ER図を完成させる。

## OutPut
・[ER図試作](https://github.com/kaitoishii1217/ToDoApp/blob/main/image/ER%E5%9B%B3.pdf)
・[ER図完成形](https://github.com/kaitoishii1217/ToDoApp/blob/main/image/Todo%E3%82%A2%E3%83%97%E3%83%AAER%E5%9B%B3.png)

**Comment by itpm-sakamoto** [comment]
ER図完成の為、Closeします。
