### ISSUE TITLE
[todoapp][実装]データベースの作成

### ISSUE THREAD

**Issue by kaitoishii1217** [kaitoishii1217/ToDoApp#8]
## 概要
・ToDoアプリで使用するデータベースを作成する。

## 計画
・ER図に従ってテーブルを作成する。
・カラムを定義する。
・主キーを設定する。

作業開始：6/30
作業終了：7/1

## ゴール
・データベースを完成させる。

## OutPut
・ToDoアプリ用データベース

**Comment by itpm-sakamoto** [comment]
データベース作成完了の為、Closeします。
